server:
  port: 8200
  
spring:
  datasource:
    url: "jdbc:h2:mem:passenger"
    driverClassName: "org.h2.Driver"
    username: sa
    password: password
  h2: 
    console:
      path: "/h2-console"
      enabled: "true"
      settings:
        trace: "false"
        web-allow-others: "false"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    defer-datasource-initialization: "true"
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        format-sql: "true"
  sql:
    init.mode: "always"
